### ISSUE TITLE
geolink_elevation()

### ISSUE THREAD

**Issue by dasalm20** [SSA-Statistical-Team-Projects/GeoLink#37]
Dear @DianaJaganjac  and @ifeanyi588, 

I tried testing elevation but it seems like it is not properly reading the rasters. I get an error message : 

**Error in raster_objs[[1]] : subscript out of bounds**

When I debugged, the issue might be between lines 836- 854 of geolink_mach.R . The tif image is downloaded but when the function tries to list the files in the temp directory, it returns an empty object. 

Best, 
Daylan

**Comment by dasalm20** [comment]
The cropland function has the same issue. So any other function that uses the same system to read in the rasters, will have the the issue.

**Comment by dasalm20** [comment]
Dear @DianaJaganjac  and @ifeanyi588, 

I do not think the issue has to do with the API because it downloads a raster. The issues seems to be when using the temporary directory. 


<img width="656" alt="Screenshot 2024-07-03 at 10 00 39 AM" src="https://github.com/SSA-Statistical-Team-Projects/GeoLink/assets/68434183/a52a124f-a754-4766-874d-be6e1da6ab3a">

**Comment by DianaJaganjac** [comment]
Hi Daylan, I have fixed this for both elevation and cropland.

**Comment by dasalm20** [comment]
Dear @DianaJaganjac

Thanks for fixing the issue with elevation and cropland. The function works for a shapefile but it does not work for a survey. Did you check running it for a survey? 



I am getting this error: 


test_dt <- geolink_elevation(survey_dt =  st_as_sf(hhgeo_dt[1:10],
+                                                                         crs = 4326),
+                                                   buffer_size = 1000,
+                                                   extract_fun = "mean")

Error in geolink_elevation(survey_dt = st_as_sf(hhgeo_dt[1:10], crs = 4326),  : 
  argument "shp_dt" is missing, with no default


Even when I set the values to NULL, it does not work. Is it supposed to work on shapefile only ?
